---
title: "Browser History Graph"
author: "Dylan Sun"
date: "July 23, 2016"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, results = "hide")
```

## Load browsing history data

```{r}
library(jsonlite)
library(data.table)
bhistory <- fromJSON("/Users/dsun/Google Drive/Takeout/Takeout 2/Chrome/BrowserHistory.json")
dt <- data.table(bhistory)
rm(bhistory)
```

## Format browser history
```{r}
url.regex = "^https?://([^/]+)/(.*)$"
dt[, date_time := as.POSIXct(time_usec/1000000, tz = "EST", origin = "1970-01-01")]
dt[, month := as.numeric(format(date_time, "%m"))]
dt[, year := as.numeric(format(date_time, "%y"))]
dt[, host := gsub(url.regex, "\\1", url)]
```

## Line graph
### Prep data for line graph
We want a table with the top q most visited sites (determined by counting instances of the host name) for each year-month.
```{r}
library(zoo)
q = 5L
line.graph.data = dt[, .(count=.N), by = c("year","month","host")][order(year,month,-count)][, lapply(.SD, function(x) head(x, n=q)), by = c("year","month")]
line.graph.data[, month_year := as.yearmon(paste(month, year, sep="-"), "%m-%y")]
```
```{r, results = "markup"}
head(line.graph.data)
```

### Produce line graph
Used [this website](http://www.cookbook-r.com/Graphs/Bar_and_line_graphs_(ggplot2)/) as a reference for producing this graph.
```{r browser_history_line_graph}
library(ggplot2)
ggplot(data=line.graph.data, aes(x=factor(month_year, labels = unique(format(month_year, "%m-%y"))), y=count, group=host, color=host, label=host)) +
    geom_line() +
    geom_point() +
    labs(y = "Visits", x = "Month") + 
    ggtitle("This is what I do apparently")
```